name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install necessary dependencies to run the notebook
      - name: Install Python, Jupyter, and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install notebook
          pip3 install -r requirements.txt

      # Run the Jupyter notebook
      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute "ML Algo.ipynb" --output "ML Algo_output.ipynb"

      # Optional: Upload the executed notebook as an artifact (if needed)
      - name: Upload Notebook as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: ML Algo_output.ipynb
